### ISSUE TITLE
MClassifier: Sign docker image

### ISSUE THREAD

**Issue by martinkearn** [buerokratt/Mock-Classifier#23]
AS A devops engineer
I WANT to sign the mock classifier docker image that is built in the CI pipeline
SO THAT we deploy trusted images in the CD pipeline

Pre-requisite: we need a certificate from an appropriate certificate authority before we can play this issue

## Acceptance Criteria
- [x] Create/update a pipeline to sign the docker image
- [x] The signing flow is following https://github.blog/2021-12-06-safeguard-container-signing-capability-actions/
- [x] The signature should contain reference to commit SHA

**Comment by keijoraamat** [comment]
https://github.blog/2021-12-06-safeguard-container-signing-capability-actions/

> This means you can sign your container images with the GitHub-provided OIDC token in Actions, without provisioning or 
> managing your own private key. This is critically what makes signing so easy that we can turn it on by default, because there’s no additional setup beyond adding a specific GitHub Actions workflow.

> This keyless signing includes Rekor, a public transparency log, meaning your username, organization name, repository name, and workflow name will be published to the public transparency log. 
So in a nutshell, GitHub basically provides CA for signing images. No need for separate certificate for signing.

**Comment by martinkearn** [comment]
@keijoraamat This is good news. However, there are still some things we need to obtain before this can be incorporated into the CI pipeline such as the signing secret? Perhaps you could update the AC for this task to reflect what needs to be done in light of this discovery?
